/**
 * ZONA-OSIER — ObjectBox Generated Class Stub.
 *
 * Class ini di-generate otomatis oleh ObjectBox Gradle plugin saat build pertama kali.
 * File ini HANYA stub untuk review. ObjectBox plugin akan overwrite
 * versi sebenarnya di build/ generated sources.
 *
 * Jika build gagal dengan "Unresolved reference: MyObjectBox",
 * jalankan: ./gradlew :android:app:clean :android:app:assembleDebug
 */
package com.zonaosier

import android.content.Context
import io.objectbox.BoxStore

/**
 * Stub class. ObjectBox plugin generates the real version.
 * The generated class will have: MyObjectBox.builder().androidContext(ctx).build()
 */
@Suppress("unused")
object MyObjectBox {
    /**
     * Creates a new BoxStore Builder.
     * The real implementation is generated by the ObjectBox Gradle plugin.
     */
    @JvmStatic
    fun builder(): BoxStore.Builder {
        // ObjectBox plugin will replace this with generated code.
        // If you see this at runtime, ObjectBox was not properly initialized.
        return BoxStore.builder()
    }
}
